kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sofa-test
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30081
    hostPort: 30081
    protocol: TCP
  - containerPort: 30082
    hostPort: 30082
    protocol: TCP
