apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
- ../../base

patchesStrategicMerge:
- sofa-config-patch.yaml
- resources-patch.yaml
- keycloak-service-patch.yaml
- keycloak-deployment-patch.yaml

# Sets the image tag for production deployment
images:
- name: sofa
  newName: sofa
  newTag: stable
