apiVersion: v1
kind: ConfigMap
metadata:
  name: sofa-config
data:
  auth_enabled: "false"
  # The following settings are ignored when auth_enabled is false
  auth_issuer: ""
  auth_audience: ""
  auth_jwks_url: ""
  # Audit configuration
  audit_enabled: "false"
  audit_log_service_url: ""
  # Note: master_enc_key is stored in a Secret, not in this ConfigMap
  # Encrypted endpoints - comma-separated list of regex patterns
  encrypted_endpoints: "^/secure/.*,^/api/private/.*"
