apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofa
  labels:
    app: sofa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofa
  template:
    metadata:
      labels:
        app: sofa
    spec:
      containers:
      - name: sofa
        image: sofa:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: SOFA_COUCHDB_URL
          value: "http://couchdb-service:5984"
        - name: SOFA_COUCHDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchdb-credentials
              key: username
        - name: SOFA_COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-credentials
              key: password
        # OAuth2 Configuration
        - name: SOFA_AUTH_ENABLED
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_enabled
              optional: true
        - name: SOFA_AUTH_ISSUER
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_issuer
              optional: true
        - name: SOFA_AUTH_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_audience
              optional: true
        - name: SOFA_AUTH_JWKS_URL
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_jwks_url
              optional: true
        # New Istio-like Authorization Rules
        - name: SOFA_AUTH_AUTHORIZATION
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_authorization
              optional: true
        # Audit Configuration
        - name: SOFA_AUDIT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: audit_enabled
              optional: true
        - name: SOFA_AUDIT_LOG_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: audit_log_service_url
              optional: true
        # Encryption Configuration
        - name: SOFA_MASTER_ENC_KEY
          valueFrom:
            secretKeyRef:
              name: sofa-secrets
              key: master_enc_key
              optional: true
        - name: SOFA_ENCRYPTED_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: encrypted_endpoints
              optional: true
        # Proxy Configuration
        - name: SOFA_PROXY_HEADERS_REMOVE
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: proxy_headers_remove
              optional: true
        - name: SOFA_PROXY_PRESERVE_HOST
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: proxy_preserve_host
              optional: true
        - name: SOFA_CHUNKED_ENCODING
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: chunked_encoding
              optional: true
        - name: SOFA_PROXY_BUFFER_SIZE
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: proxy_buffer_size
              optional: true
        - name: SOFA_PROXY_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: proxy_timeout
              optional: true
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
