version: '3'

vars:
  CLUSTER_NAME: sofa-test
  IMAGE_NAME: sofa:latest
  NAMESPACE: default
  SOFA_PORT: 3000
  DEX_PORT: 30556
  ENVIRONMENT: dev # default environment

tasks:
  build:
    desc: Build the Sofa Docker image
    cmds:
    - echo "Building Sofa Docker image..."
    - docker build -t {{.IMAGE_NAME}} .

  create-cluster:
    desc: Create a Kind cluster if it doesn't exist
    cmds:
    - |
      if ! kind get clusters | grep -q {{.CLUSTER_NAME}}; then
        echo "Creating Kind cluster..."
        kind create cluster --name {{.CLUSTER_NAME}}
      else
        echo "Kind cluster already exists, skipping creation."
      fi

  load-image:
    desc: Load the Sofa image into the Kind cluster
    deps: [ build, create-cluster ]
    cmds:
    - echo "Loading Sofa image into Kind cluster..."
    - kind load docker-image {{.IMAGE_NAME}} --name {{.CLUSTER_NAME}}

  apply-manifests:
    desc: Apply all Kubernetes manifests using Kustomize
    deps: [ load-image ]
    cmds:
    - echo "Applying Kubernetes resources using Kustomize for {{.ENVIRONMENT}} environment..."
    - kubectl apply -k k8s/overlays/{{.ENVIRONMENT}}
    - |
      echo "Waiting for services to be ready..."
      kubectl wait --for=condition=available deployment/{{.ENVIRONMENT}}-couchdb --timeout=90s || true
      kubectl wait --for=condition=available deployment/{{.ENVIRONMENT}}-dex --timeout=90s || true
      kubectl wait --for=condition=available deployment/{{.ENVIRONMENT}}-sofa --timeout=90s || true

  port-forward:
    desc: Port-forward Sofa and Dex services to local ports
    deps: [ apply-manifests ]
    cmds:
    - |
      # Kill any existing port-forwards
      pkill -f "kubectl port-forward" || true
      sleep 1

      # Start port forwarding in the background
      kubectl port-forward svc/{{.ENVIRONMENT}}-sofa-service {{.SOFA_PORT}}:80 &
      echo "Sofa available at http://localhost:{{.SOFA_PORT}}"

      # Use the NodePort for Dex in dev environment
      kubectl port-forward svc/{{.ENVIRONMENT}}-dex-nodeport {{.DEX_PORT}}:5556 &
      echo "Dex available at http://localhost:{{.DEX_PORT}}/dex"

      echo "Press Ctrl+C to stop port-forwarding"
      # Keep the task running to maintain port-forwards
      tail -f /dev/null
    interactive: true

  run-test:
    desc: Run the OAuth2 test client directly against the cluster (no port-forward needed)
    deps: [ apply-manifests ]
    cmds:
    - |
      echo "Applying test environment manifests and test client..."
      kubectl apply -k k8s/overlays/test

      echo "Waiting for test job to complete..."
      kubectl wait --for=condition=complete job/test-sofa-test-client --timeout=60s || true

      # Show logs from the test job
      echo "Test job logs:"
      kubectl logs job/test-sofa-test-client

  run-test-local:
    desc: Run the OAuth2 test client locally (requires port-forwarding)
    cmds:
    - |
      export DEX_URL="http://localhost:{{.DEX_PORT}}/dex"
      export SOFA_URL="http://localhost:{{.SOFA_PORT}}"
      export CLIENT_ID="sofa-client"
      export CLIENT_SECRET="sofa-client-secret"
      cargo run --bin oauth_client

  setup:
    desc: Complete setup - build, create cluster, load image, and apply manifests
    deps: [ load-image, apply-manifests ]
    cmds:
    - echo "Setup complete! Run 'task port-forward' to access services and 'task run-test' to test OAuth2 authentication."

  switch-env:
    desc: Switch the active environment (dev, test, prod)
    interactive: true
    cmds:
    - |
      if [ -z "{{.CLI_ARGS}}" ]; then
        echo "Usage: task switch-env -- [dev|test|prod]"
        exit 1
      fi

      if [ "{{.CLI_ARGS}}" != "dev" ] && [ "{{.CLI_ARGS}}" != "test" ] && [ "{{.CLI_ARGS}}" != "prod" ]; then
        echo "Invalid environment. Please specify one of: dev, test, prod"
        exit 1
      fi

      # Create a temporary file with updated vars
      cat > .env.temp << EOF
      ENVIRONMENT={{.CLI_ARGS}}
      EOF

      echo "Environment switched to {{.CLI_ARGS}}"

      # Prompt to apply changes immediately
      read -p "Do you want to apply changes immediately? (y/n) " apply
      if [ "$apply" = "y" ] || [ "$apply" = "Y" ]; then
        task apply-manifests ENVIRONMENT={{.CLI_ARGS}}
      fi

  show-env:
    desc: Show the current environment
    cmds:
    - |
      echo "Current environment: {{.ENVIRONMENT}}"

  default:
    desc: Display help information
    cmds:
    - task --list
