apiVersion: apps/v1
kind: Deployment
metadata:
  name: sofa
  labels:
    app: sofa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sofa
  template:
    metadata:
      labels:
        app: sofa
    spec:
      containers:
      - name: sofa
        image: sofa:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: SOFA_COUCHDB_URL
          value: "http://couchdb-service:5984"
        - name: SOFA_COUCHDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: couchdb-credentials
              key: username
        - name: SOFA_COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-credentials
              key: password
        # OAuth2 Configuration
        - name: SOFA_AUTH_ENABLED
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_enabled
              optional: true
        - name: SOFA_AUTH_ISSUER
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_issuer
              optional: true
        - name: SOFA_AUTH_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_audience
              optional: true
        - name: SOFA_AUTH_JWKS_URL
          valueFrom:
            configMapKeyRef:
              name: sofa-config
              key: auth_jwks_url
              optional: true
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: sofa-service
spec:
  selector:
    app: sofa
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: couchdb-credentials
type: Opaque
stringData:
  username: admin
  password: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sofa-config
data:
  auth_enabled: "false"
  # Uncomment and set these values for OAuth2 authentication
  # auth_issuer: "https://your-auth-server.com"
  # auth_audience: "your-api-audience"
  # auth_jwks_url: "https://your-auth-server.com/.well-known/jwks.json"
