apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      containers:
      - name: keycloak
        env:
        - name: KC_HOSTNAME
          value: "localhost:30082" # Hardcoded port for dev environment 
