apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- ../../base

# Generate dev-specific secrets
secretGenerator:
- behavior: replace
  literals:
  - master_enc_key=dev-environment-secure-encryption-key-2025
  name: sofa-secrets
- behavior: replace
  literals:
  - master_key=hsm-simulator-master-key-for-development-only
  name: hsm-simulator-secret


# Sets the image tag to :latest for all component images
# This is appropriate for dev environment with frequent changes
images:
- name: sofa
  newName: sofa
  newTag: latest
- name: hsm-simulator
  newName: hsm-simulator
  newTag: latest
patches:
- path: sofa-deployment-patch.yaml
- path: sofa-config-patch.yaml
- path: keycloak-config-patch.yaml
- path: keycloak-deployment-patch.yaml
- path: keycloak-service-patch.yaml
- path: hsm-simulator-patch.yaml
