apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- ../../base
- hsm-simulator-patch.yaml

# Generate dev-specific secrets
secretGenerator:
- name: sofa-secrets
  behavior: replace
  literals:
  - master_enc_key=dev-environment-secure-encryption-key-2025
- name: hsm-simulator-secret
  behavior: create
  literals:
  - master_key=hsm-simulator-master-key-for-development-only

patchesStrategicMerge:
- sofa-deployment-patch.yaml
- sofa-config-patch.yaml
- keycloak-config-patch.yaml
- keycloak-deployment-patch.yaml
- keycloak-service-patch.yaml

# Sets the image tag to :latest for all component images
# This is appropriate for dev environment with frequent changes
images:
- name: sofa
  newName: sofa
  newTag: latest
- name: hsm-simulator
  newName: hsm-simulator
  newTag: latest
