apiVersion: v1
kind: ConfigMap
metadata:
  name: sofa-config
data:
  auth_enabled: "true"
  # Dev-specific configuration - uses the prefixed service names
  auth_issuer: "http://localhost:30082/realms/sofa"
  auth_jwks_url: "http://dev-keycloak-service:8080/realms/sofa/protocol/openid-connect/certs"
  auth_audience: "topology"
  audit_enabled: "true"
  audit_log_service_url: "http://dev-audit-service:8080/logs"
