apiVersion: v1
kind: ConfigMap
metadata:
  name: sofa-config
data:
  auth_enabled: "true"
  # Development configuration for Keycloak URLs
  # Issuer must match the URL from which tokens are issued
  auth_audience: "sofa-client"
  # JWKS URL must be reachable by Sofa for token validation
  auth_jwks_url: "http://dev-keycloak-service:8080/realms/sofa/protocol/openid-connect/certs"

  # New Istio-like Authorization Rules
  auth_authorization: |
    default_action: deny
    rules:
      # Rule 1: Admin users get full access
      - name: "admin-full-access"
        when:
          - claim: "role"
            values: "admin"
      
      # Rule 2: Regular users with organization and role claims
      - name: "user-database-access"
        paths:
          - "^/[^_][^/]+/.*"           # Database documents
          - "^/[^_][^/]+/_design/.*"   # Design documents
          - "^/[^_][^/]+/_bulk_docs"   # Bulk operations
          - "^/[^_][^/]+/_find"        # Find operations
          - "^/[^_][^/]+/_index"       # Index operations
        when:
          - claim: "organization"
            values: "Sofa Organization"
          - claim: "role"
            values: ["user", "admin"]
      
      # Rule 3: Database creation permission
      - name: "database-creation"
        methods: ["PUT"]
        paths:
          - "^/[^_][^/]+/?$"  # Database creation endpoint
        when:
          - claim: "db_create"
            values: true
          - claim: "role"
            values: ["admin", "user"]
      
      # Rule 4: System database read access (for topology client)
      - name: "system-database-read"
        methods: ["GET", "HEAD"]
        paths:
          - "^/_all_dbs$"       # List all databases
          - "^/_.*"             # System endpoints
        when:
          - claim: "role"
            values: ["admin", "user"]
      
      # Rule 5: User authentication check endpoints
      - name: "auth-endpoints"
        paths:
          - "^/_session$"
          - "^/_users/.*"
        when:
          - claim: "role"
            values: ["admin", "user"]

  # Encryption configuration for development
  encrypted_endpoints: "^/[^_][^/]+/[^_].*,^/[^_][^/]+/_design/.*,^/[^_][^/]+/_bulk_docs,^/[^_][^/]+/_find,^/[^_][^/]+/_index"
  # Enable HSM integration
  encryption_hsm: "true"
  # Feature-specific HSM configuration (These are read by main.rs directly)
  # HSM simulator specific config (used only with hsm-simulator feature)
  SOFA_HSM_SIMULATOR_URL: "http://dev-hsm-simulator:8080"
  SOFA_HSM_KEY_NAME: "sofa-master-key"
  # Azure HSM specific config (used only with azure-hsm feature)
  SOFA_HSM_AZURE_KEYVAULT_URL: "https://your-keyvault.vault.azure.net"
  SOFA_HSM_AZURE_KEY_NAME: "sofa-master-key"
  # Proxy configuration to fix "empty reply from server" issue
  proxy_headers_remove: "transfer-encoding"
  proxy_preserve_host: "true"
  chunked_encoding: "false"
  proxy_buffer_size: "10mb"
  proxy_timeout: "60000"
